import { test, expect } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
test('home harbor animates, stays behind controls and supports reduced motion', async ({page})=>{
  test.setTimeout(90000);
  const errors:string[]=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  await page.goto('/?diagnostics=1');
  const canvas=page.locator('.harbor-backdrop canvas');
  await expect.poll(async()=>Number(await canvas.getAttribute('data-frames'))).toBeGreaterThan(5);
  const sample=async()=>canvas.evaluate(e=>({...e.dataset}));
  const before=await sample();
  await page.waitForTimeout(3000);
  const after=await sample();
  expect(after.beacon).not.toBe(before.beacon);expect(after.shipX).not.toBe(before.shipX);expect(after.time).not.toBe(before.time);
  await page.screenshot({path:'artifacts/harbor-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Войти',exact:true}).click();
  await expect(page.getByLabel('Логин или почта')).toBeVisible();
  await page.getByRole('button',{name:'На стартовый экран'}).click();
  await page.getByRole('button',{name:'Создать аккаунт',exact:true}).click();
  await expect(page.getByLabel('Логин',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'На стартовый экран'}).click();
  await page.setViewportSize({width:390,height:844});
  await expect(page.getByRole('button',{name:'Играть с ботом',exact:true})).toBeInViewport();
  await page.waitForTimeout(1000);
  await page.screenshot({path:'artifacts/harbor-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.waitForTimeout(600);
  const staticBefore=await sample();await page.waitForTimeout(1000);const staticAfter=await sample();
  expect(staticAfter.frames).toBe(staticBefore.frames);
  await page.screenshot({path:'artifacts/harbor-reduced.png',fullPage:true});
  await writeFile('artifacts/harbor-performance.json',JSON.stringify({desktopFramesIn3Seconds:Number(after.frames)-Number(before.frames),drawCalls:after.drawCalls,triangles:after.triangles,staticFrames:Number(staticAfter.frames)-Number(staticBefore.frames),note:'Chrome headless, 1920x1080 and 390x844; no physical device measurement.'},null,2));
  expect(errors).toEqual([]);
});
