import {Anchor, BookOpen, Crosshair, Radio, Volume2} from 'lucide-react';
import {t,useLanguage} from './i18n';
import {catalog} from './shop/catalog';
import {emotions,emotionImage} from './emotions/catalog';
import './guide.css';

const copy={
  ru:{title:'Ваш первый выход в море',eyebrow:'СПРАВОЧНИК КАПИТАНА',intro:'От расстановки флота до последнего залпа. Всё, что нужно знать о «Флоте: Сектор 10».',play:'Начать тренировку',back:'Вернуться',sections:['Быстрый старт','Правила боя','Игра с другом','Карты и магазин','Эмоции и звук','Профиль и сохранения'],steps:[['Выберите противника','С ботом можно играть без регистрации. Выберите сложность перед началом партии. Для боя с другом войдите в свой аккаунт.'],['Разверните флот','Нажмите «Авторасстановка» или выберите корабль и клетку. Кнопка «Повернуть» меняет направление. Когда готовы все 10 кораблей, начинайте бой.'],['Отдайте приказ','В свой ход нажмите свободную клетку противника. На телефоне используйте увеличенное поле. Оранжевый след — попадание, светлая отметка — промах.']],rules:['Поле 10×10. Флот: 4 катера по 1 клетке, 3 корвета по 2, 2 эсминца по 3 и 1 авианосец на 4 клетки. Всего 20 сегментов.','Корабли прямые. Между ними должна оставаться вода: нельзя соприкасаться даже углами.','Попадание даёт ещё один ход, промах передаёт ход сопернику. Повторный выстрел в ту же клетку недоступен.','После потопления всего корабля крестики отмечают безопасную воду вокруг него. Это подсказки, а не дополнительные выстрелы.','Уничтожьте все 10 кораблей противника, чтобы победить.'],friend:'Оба игрока входят в разные аккаунты. Первый выбирает «Играть с другом» → «Создать комнату» и копирует приглашение. Второй открывает ссылку и присоединяется. Расставьте флоты: бой начнётся, когда готовы оба.',reconnect:'При обновлении страницы матч сохраняется. Если связь прервалась, дождитесь восстановления. Кнопка «Вернуться в бой» открывает вашу комнату. После результата можно предложить реванш.',cards:'Купленные экземпляры хранятся в вашем арсенале. Во время своего хода выберите доступную карту в компактной панели. Для области укажите клетку на поле; отмена или Esc не расходуют карту. Пока вы выбираете цель, обычный выстрел не производится.',classic:'Если комната показывает классический бой, в ней доступны только обычные выстрелы. Наличие карт проверяйте по панели конкретной партии.',audio:'Все шесть эмоций бесплатны. Откройте кнопку «Эмоции» рядом с полем и выберите капитана. Соперник увидит его в сетевом бою. Между отправками — пауза 3 секунды.',settings:'Первое нажатие на странице включает звук, если он разрешён вами. Значок динамика выключает всё, а меню ♫ отдельно управляет морем, боевыми эффектами и голосом. Настройки сохраняются. Для спокойной сцены включите «Спокойное море» или уменьшение движения в системе.',profile:'Гостевой прогресс хранится в этом браузере. Аккаунт сохраняет профиль, валюту и покупки на сервере. Входите в тот же аккаунт на другом устройстве. История боёв с ботом и рейтинг матчей с другом учитываются отдельно. Никогда не передавайте пароль вместе со ссылкой комнаты.',legend:['Потоплен','Попадание','Промах','Безопасная вода'],credits:'Звуки и авторы'},
  en:{title:'Your first voyage',eyebrow:'CAPTAIN’S HANDBOOK',intro:'From deploying your fleet to the final salvo. Your guide to Fleet: Sector 10.',play:'Start training',back:'Back',sections:['Quick start','Battle rules','Play with a friend','Cards and shop','Reactions and audio','Profile and saves'],steps:[['Choose an opponent','Play a bot without an account and select its difficulty. Sign in to play a friend.'],['Deploy your fleet','Use Auto placement or choose a ship and a cell. Rotate changes its direction. Deploy all 10 ships, then start.'],['Give the order','On your turn, select an unshot enemy cell. Use the enlarged board on a phone. Orange marks a hit; a light marker means a miss.']],rules:['A 10×10 board, with four 1-cell patrol boats, three 2-cell corvettes, two 3-cell destroyers and one 4-cell carrier: 20 segments.','Ships are straight and cannot touch, even diagonally.','A hit grants another turn; a miss passes the turn. You cannot shoot the same cell twice.','Only fully sunk ships receive safe-water crosses around them. These are hints, not extra shots.','Sink all 10 enemy ships to win.'],friend:'Both players sign in to separate accounts. Choose Play with a friend → Create room, then copy the invitation. Your friend opens it and joins. The battle starts once both fleets are ready.',reconnect:'Reloading keeps your match. Wait for reconnection after a brief interruption. Return to battle reopens your room. Offer a rematch after the result.',cards:'Purchased copies stay in your arsenal. On your turn, select an available card in the battle panel. Target an area on the board; Cancel or Esc spends nothing. A normal shot will not fire while targeting a card.',classic:'Rooms marked as classic allow ordinary shots only. Check the panel in your match for available cards.',audio:'All six reactions are free. Open Emotions beside the board and select a captain. Your friend sees the same reaction online. There is a 3-second cooldown.',settings:'Your first interaction enables audio if you have allowed it. The speaker mutes everything; ♫ controls sea, battle and voice separately. Settings persist. Choose Calm sea or your system’s reduced-motion setting for a quieter scene.',profile:'Guest progress stays in this browser. An account saves your profile, currency and purchases on the server. Use the same account on another device. Bot records and friend-match rankings are separate. Never share your password with a room link.',legend:['Sunk','Hit','Miss','Safe water'],credits:'Audio credits'},
  kk:{title:'Теңізге алғашқы сапар',eyebrow:'КАПИТАН АНЫҚТАМАЛЫҒЫ',intro:'Флотты орналастырудан соңғы атысқа дейін. «Флот: Сектор 10» ойынына арналған нұсқаулық.',play:'Жаттығуды бастау',back:'Артқа',sections:['Жылдам бастау','Ұрыс ережелері','Доспен ойнау','Карталар мен дүкен','Эмоциялар мен дыбыс','Профиль және сақтау'],steps:[['Қарсылас таңдаңыз','Ботпен тіркелмей ойнауға және қиындық деңгейін таңдауға болады. Доспен ойнау үшін аккаунтқа кіріңіз.'],['Флотты орналастырыңыз','Автоматты орналастыруды пайдаланыңыз немесе кеме мен ұяшықты таңдаңыз. «Бұру» бағытын өзгертеді. Барлық 10 кеме дайын болғанда бастаңыз.'],['Бұйрық беріңіз','Өз кезегіңізде қарсыластың бос ұяшығын таңдаңыз. Телефонда үлкейтілген алаңды пайдаланыңыз. Қызғылт сары — тиді, ақ белгі — мүлт кетті.']],rules:['10×10 алаң: төрт 1 ұяшықты катер, үш 2 ұяшықты корвет, екі 3 ұяшықты эсминец және бір 4 ұяшықты авианосец. Барлығы 20 бөлік.','Кемелер түзу орналасады және бір-біріне бұрыштарымен де жанаспайды.','Тигізсеңіз, қайта атасыз. Мүлт кетсе, кезек қарсыласқа өтеді. Бір ұяшыққа екі рет атуға болмайды.','Кеме толық батқанда ғана айналасындағы қауіпсіз су крестпен белгіленеді. Бұл қосымша атыс емес.','Жеңу үшін қарсыластың барлық 10 кемесін батырыңыз.'],friend:'Екі ойыншы бөлек аккаунтқа кіреді. «Доспен ойнау» → «Бөлме құру» арқылы шақыру сілтемесін көшіріңіз. Досыңыз оны ашып, қосылады. Екі флот дайын болғанда ұрыс басталады.',reconnect:'Бетті жаңартқанда матч сақталады. Байланыс үзілсе, қайта қосылуын күтіңіз. «Ұрысқа оралу» бөлмені ашады. Нәтижеден кейін реванш ұсынуға болады.',cards:'Сатып алынған карталар арсеналда сақталады. Өз кезегіңізде ұрыс панелінен қолжетімді картаны таңдаңыз. Аймақты алаңда көрсетіңіз; бас тарту немесе Esc картаны жұмсамайды. Нысана таңдау кезінде кәдімгі атыс болмайды.',classic:'Классикалық бөлмеде тек кәдімгі атыстар бар. Қолжетімді карталарды матч панелінен тексеріңіз.',audio:'Алты эмоция да тегін. Алаң жанындағы «Эмоциялар» батырмасын ашып, капитанды таңдаңыз. Досыңыз желіде сол эмоцияны көреді. Жіберулер арасында 3 секунд үзіліс бар.',settings:'Рұқсат берсеңіз, беттегі алғашқы әрекет дыбысты қосады. Динамик барлық дыбысты өшіреді; ♫ мәзірі теңізді, ұрыс пен дауысты бөлек басқарады. Баптаулар сақталады. Қозғалысты азайту үшін тыныш теңізді немесе жүйелік баптауды таңдаңыз.',profile:'Қонақтың жетістігі осы браузерде сақталады. Аккаунт профильді, валютаны және сатып алуларды серверде сақтайды. Басқа құрылғыда сол аккаунтқа кіріңіз. Ботпен статистика және достармен рейтинг бөлек есептеледі. Бөлме сілтемесімен бірге құпиясөзді жібермеңіз.',legend:['Батты','Тиді','Мүлт','Қауіпсіз су'],credits:'Дыбыс авторлары'},
};
export default function Guide({back,play}:{back:()=>void;play:()=>void}){
  const {language}=useLanguage(),c=copy[language];
  return <article className="guide-page">
    <header><div><small><BookOpen size={16}/> {c.eyebrow}</small><h1>{c.title}</h1><p>{c.intro}</p></div><button className="button secondary" onClick={back}>{c.back}</button></header>
    <nav aria-label={c.eyebrow}>{c.sections.map((s,i)=><a key={s} href={`#guide-${i}`}>{String(i+1).padStart(2,'0')} · {s}</a>)}</nav>
    <section id="guide-0"><h2><Anchor/>{c.sections[0]}</h2><div className="guide-steps">{c.steps.map(([title,body],i)=><div key={title}><b>0{i+1}</b><h3>{title}</h3><p>{body}</p></div>)}</div><button className="button primary" onClick={play}>{c.play}</button></section>
    <section id="guide-1"><h2><Crosshair/>{c.sections[1]}</h2><div className="guide-rules"><div><ul>{c.rules.map(s=><li key={s}>{s}</li>)}</ul></div><figure><div className="guide-demo" aria-hidden="true">{Array.from({length:25},(_,i)=><span key={i} className={i===6||i===7?'ship':i===24?'hit':i===19?'miss':[0,1,2,3,5,8,10,11,12,13].includes(i)?'safe':''}>{[6,7,24].includes(i)?'✹':i===19?'•':[0,1,2,3,5,8,10,11,12,13].includes(i)?'×':''}</span>)}</div><figcaption>{c.legend.map((s,i)=><span key={s}><i className={['ship','hit','miss','safe'][i]}/>{s}</span>)}</figcaption></figure></div></section>
    <section id="guide-2"><h2><Radio/>{c.sections[2]}</h2><p>{c.friend}</p><p>{c.reconnect}</p></section>
    <section id="guide-3"><h2>{c.sections[3]}</h2><p>{c.cards}</p><p className="guide-note">{c.classic}</p><div className="guide-cards">{catalog.filter(item=>item.kind==='card').map(item=><div key={item.id}><strong>{item.icon} {t(item.name)}</strong><p>{t(item.description)}</p></div>)}</div></section>
    <section id="guide-4"><h2><Volume2/>{c.sections[4]}</h2><p>{c.audio}</p><div className="guide-emotions">{emotions.map(e=><figure key={e.id}><img src={emotionImage(e.id)} width="64" height="64" alt="" loading="lazy"/><figcaption>{t(e.name)}</figcaption></figure>)}</div><p>{c.settings}</p></section>
    <section id="guide-5"><h2>{c.sections[5]}</h2><p>{c.profile}</p></section>
    <details className="guide-credits"><summary>{c.credits}</summary><p>Battle at Sea — Thimras (CC0). Piper: Dmitri, Joe (CC0); KazakhTTS / ISSAI (CC BY 4.0). {language==='ru'?'Реплики синтезированы заранее и воспроизводятся из файлов.':'Offline generated voice recordings.'}</p><a href="/audio/CREDITS.txt" target="_blank" rel="noreferrer">Credits &amp; licenses</a></details>
  </article>;
}
